"""Change in oter_item table

Revision ID: 23fb2640c8fa
Revises: f3fe35f6ef09
Create Date: 2025-09-22 23:36:11.145494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23fb2640c8fa'
down_revision: Union[str, Sequence[str], None] = 'f3fe35f6ef09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
